### ISSUE TITLE
Name isnt valid erro

### ISSUE THREAD

**Issue by firozozman** [alexc-MSFT/sharepoint-events-powerapp#1]
Hi Alex

Thanks for this app. I am trying to import and run in it on my tenant and getting this error:

![image](https://user-images.githubusercontent.com/15437706/135914461-8c4907d2-48e0-4019-a0f9-d94288349c8e.png)

Am I missing any steps?

**Comment by alexc-MSFT** [comment]
@firozozman Sorry for the delay in getting back to you. 

You can ignore that error. It's due to an error in a component which the app isn't actually using at the moment but it still resides in the app.

It should function fine, you can always delete the PopupDialog component from the components pane and that error should go away.

Thanks
